---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksSecret
metadata:
  name: cloud-controller-username-lookup-client-secret
  namespace: cf-system
spec:
  type: password
  secretName: cloud-controller-username-lookup-client-secret
